name: screen_share_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  flutter_riverpod: ^3.3.2
  ffmpeg_kit_flutter_new_https_gpl: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true